services:
  db:
    image: postgres:14-alpine
    container_name: formcam_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker_password
      POSTGRES_DB: formcam
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  api:
    build: .
    container_name: formcam_api
    ports:
      - "3339:3339"
    environment:
      DATABASE_URL: "postgresql://docker:docker_password@db:5432/formcam"
      JWT_SECRET: "your-super-secret-key-for-docker"
      PORT: 3339
    depends_on:
      - db
    # Override the default command to use tsx directly
    command: yarn tsx src/server.ts

  api-dev:
    build: .
    container_name: formcam_api_dev
    ports:
      - "3337:3339"
    environment:
      DATABASE_URL: "postgresql://docker:docker_password@db:5432/formcam"
      JWT_SECRET: "your-super-secret-key-for-docker-dev"
      PORT: 3339
    depends_on:
      - db
    volumes:
      # Mapeia o código da sua máquina para dentro do contêiner
      - .:/usr/src/app
      # Evita que a pasta node_modules do host sobrescreva a do contêiner
      - /usr/src/app/node_modules
    # Override the default command to install all dependencies and run dev
    command: sh -c "yarn install && yarn dev"
 
volumes:
  postgres_data: