services:
  db:
    image: postgres:14-alpine
    container_name: formcam_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker_password
      POSTGRES_DB: formcam
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  api:
    platform: linux/amd64
    build: .
    container_name: formcam_api
    ports:
      - "3336:3336"
    environment:
      DATABASE_URL: "postgresql://docker:docker_password@db:5432/formcam"
      JWT_SECRET: "your-super-secret-key-for-docker"
      PORT: 3336
    depends_on:
      - db

  api-dev:
    platform: linux/amd64
    build: .
    container_name: formcam_api_dev
    ports:
      - "3337:3336" # Mapeando para uma porta diferente no host (3337) para não conflitar com o serviço 'api'
    environment:
      DATABASE_URL: "postgresql://docker:docker_password@db:5432/formcam"
      JWT_SECRET: "your-super-secret-key-for-docker-dev"
      PORT: 3336
    depends_on:
      - db
    volumes:
      # Mapeia o código da sua máquina para dentro do contêiner
      - .:/usr/src/app
      # Evita que a pasta node_modules do host sobrescreva a do contêiner
      - /usr/src/app/node_modules
    command: yarn dev
 
volumes:
  postgres_data: